# Generated by Django 3.2.7 on 2022-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
                ('StudentEmail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('SuperAdminId', models.AutoField(primary_key=True, serialize=False)),
                ('SuperAdminName', models.CharField(max_length=500)),
                ('SuperAdminEmail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=500)),
                ('TeacherEmail', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
