# Generated by Django 3.2.7 on 2022-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restcheck', '0002_auto_20220330_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentPassword',
            field=models.CharField(default='abcd', max_length=500),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='SuperAdminPassword',
            field=models.CharField(default='abcd', max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TeacherPassword',
            field=models.CharField(default='abcd', max_length=500),
        ),
    ]
